# Generated by Django 4.1.5 on 2023-01-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0002_alter_geolocation_options_geolocation_address_and_more'),
        ('photos', '0002_remove_photoentity_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoentity',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photoentity',
            name='geolocations',
            field=models.ManyToManyField(blank=True, related_name='photos', to='geolocations.geolocation', verbose_name='Локации на фото'),
        ),
    ]
